# Generated by Django 3.1 on 2022-10-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_auto_20221018_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transantions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('orderid', models.IntegerField()),
                ('products', models.TextField()),
                ('total_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
