# Generated by Django 3.1 on 2022-10-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_auto_20221018_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transantions',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecomapp.customer'),
        ),
    ]
