# Generated by Django 3.1 on 2022-10-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0015_auto_20221018_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transantions',
            new_name='Transantion',
        ),
    ]
