# Generated by Django 3.1 on 2022-10-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_auto_20221018_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_phone_no', models.CharField(max_length=15)),
            ],
        ),
    ]
