# Generated by Django 3.1 on 2022-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0018_regularcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegLowCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='RegularCustomer',
            new_name='SegHighCustomer',
        ),
    ]
